config/routes.rb
Grit::Application.routes.draw do
  devise_for :users
  resources :user_settings

  resources :settings

  resources :contents

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :slides

  resources :endorsements

  resources :video_jobs

  resources :videos

  get "camera_tag_handler/create"

  root 'public#index'

  get '/about', to: 'public#about', as: :about
  get '/more', to: 'public#more', as: :more
  get '/share', to: 'public#share', as: :share

  post 'service/video_tag_handler', to: 'camera_tag_handler#create'

  get '/video/details/:token', to: 'public#details'

end

app/models/slide.rb
class Slide < ActiveRecord::Base
end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
  before_action :authenticate_admin_user!
  before_action :set_slide, only: [:show, :edit, :update, :destroy]

  # GET /slides
  # GET /slides.json
  def index
    @slides = Slide.all
  end

  # GET /slides/1
  # GET /slides/1.json
  def show
  end

  # GET /slides/new
  def new
    @slide = Slide.new
  end

  # GET /slides/1/edit
  def edit
  end

  # POST /slides
  # POST /slides.json
  def create
    @slide = Slide.new(slide_params)

    respond_to do |format|
      if @slide.save
        format.html { redirect_to @slide, notice: 'Slide was successfully created.' }
        format.json { render action: 'show', status: :created, location: @slide }
      else
        format.html { render action: 'new' }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slides/1
  # PATCH/PUT /slides/1.json
  def update
    respond_to do |format|
      if @slide.update(slide_params)
        format.html { redirect_to @slide, notice: 'Slide was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slides/1
  # DELETE /slides/1.json
  def destroy
    @slide.destroy
    respond_to do |format|
      format.html { redirect_to slides_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slide
      @slide = Slide.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slide_params
      params.require(:slide).permit(:image, :width, :height, :url, :order)
    end
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/views/slides/_form.html.haml
= form_for @slide do |f|
  - if @slide.errors.any?
    #error_explanation
      %h2= "#{pluralize(@slide.errors.count, "error")} prohibited this slide from being saved:"
      %ul
        - @slide.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :image
    = f.text_field :image
  .field
    = f.label :width
    = f.text_field :width
  .field
    = f.label :height
    = f.text_field :height
  .field
    = f.label :url
    = f.text_field :url
  .field
    = f.label :order
    = f.number_field :order
  .actions
    = f.submit 'Save'

app/views/slides/edit.html.haml
%h1 Editing slide

= render 'form'

= link_to 'Show', @slide
\|
= link_to 'Back', slides_path

app/views/slides/index.html.haml
%h1 Listing slides

%table
  %tr
    %th Image
    %th Width
    %th Height
    %th Url
    %th Order
    %th
    %th
    %th

  - @slides.each do |slide|
    %tr
      %td= slide.image
      %td= slide.width
      %td= slide.height
      %td= slide.url
      %td= slide.order
      %td= link_to 'Show', slide
      %td= link_to 'Edit', edit_slide_path(slide)
      %td= link_to 'Destroy', slide, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Slide', new_slide_path

app/views/slides/new.html.haml
%h1 New slide

= render 'form'

= link_to 'Back', slides_path

app/views/slides/show.html.haml
%p#notice= notice

%p
  %b Image:
  = @slide.image
%p
  %b Width:
  = @slide.width
%p
  %b Height:
  = @slide.height
%p
  %b Url:
  = @slide.url
%p
  %b Order:
  = @slide.order

= link_to 'Edit', edit_slide_path(@slide)
\|
= link_to 'Back', slides_path