config/routes.rb
Grit::Application.routes.draw do
  devise_for :users
  resources :user_settings

  resources :settings

  resources :contents

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :slides

  resources :endorsements

  resources :video_jobs

  resources :videos

  get "camera_tag_handler/create"

  root 'public#index'

  get '/about', to: 'public#about', as: :about
  get '/more', to: 'public#more', as: :more
  get '/share', to: 'public#share', as: :share

  post 'service/video_tag_handler', to: 'camera_tag_handler#create'

  get '/video/details/:token', to: 'public#details'

end

app/models/video.rb
class Video < ActiveRecord::Base
  include Tokenable
  require 'youtube_it'

  attr_accessor :youtube_url, :thumb_url

  URL_PREFIX='//www.youtube.com/watch?v='
  THUMB_PREFIX='http://img.youtube.com/vi/'
  THUMB_SUFFIX='/hqdefault.jpg'

  def self.featured_videos
    @@featured_videos ||= load_featured_videos
  end

  def self.load_featured_videos
    vs = ApplicationSettings.config['featured_videos']
    videos = []
    for v in vs
      video = self.find_by_key(v['key'])
      videos << video
    end
    videos.compact!
    @@featured_videos = videos
  end

  def self.top_viewed
    self.order(views: :desc).limit(3)
  end

  def self.top_rated
    self.order(likes: :desc).limit(3)
  end

  def self.latest
    self.order(created_at: :desc).limit(3)
  end

  def youtube_url
    URL_PREFIX+self.key
  end

  def thumb_url
    THUMB_PREFIX+self.key+THUMB_SUFFIX
  end

  def youtube_object
    @s = get_session
    @s.my_video(self.key)
  end

  def json_object
    @o = youtube_object
    @o.to_json
  end

  def pretty_json
    @j = json_object
    
  end

  def youtube_embed
    video = youtube_object
    video.embed_html5
  end

  def get_session
    @yt ||= YoutubeService.new
    @session ||= @yt.setup_session
  end

  def update_counters
    #instantiate youtube
    @yt = YoutubeService.new
    @yt

    #likes
    #views

  end
 
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_admin_user!
  before_action :set_video, only: [:edit, :update, :destroy]


  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render action: 'show', status: :created, location: @video }
      else
        format.html { render action: 'new' }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params[:video]
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.haml
= form_for @video, builder: LabellingFormBuilder do |f|
  - if @video.errors.any?
    #error_explanation
      %h2= "#{pluralize(@video.errors.count, "error")} prohibited this video from being saved:"
      %ul
        - @video.errors.full_messages.each do |msg|
          %li= msg
  = f.text_field :key
  = f.text_field :name
  = f.email_field :email
  .actions
    = f.submit 'Save'

app/views/videos/detail.html.haml
/ Feed layout graph object /

%section#video-player
  .video-wrap
    .youtube-holder
      %iframe.youtube{src: "http://www.youtube.com/embed/#{video.key}", frameborder: "0",  width: "1170", height: "580"}

%section#video-details
  %h2
    = video.name || "Untitled"
  %ul.stats
    %li.views
      = icon('eye-open')
      = video.views.to_s
    %li.likes
      = icon('heart')
      = video.views.to_s

%section#share-embed
  .share.pull-left
    %ul.share-box.addthis_toolbox.addthis_default_style{"addthis:url" => "http://thisisgrit.us/video/detail/#{video.token}", "addthis:title" => "Awesome grit video from #{video.name}"}                
      %li
        %a.addthis_button_facebook_like{"fb:like:layout" => "button_count"}
      %li
        %a.addthis_button_tweet{"tw:via" => "thisisgrit", "tw:count" => "none"}
      %li
        %a.addthis_counter.addthis_pill_style{}
  .embed.pull-right
    %table
      %tr
        %th
          Share URL:
        %td
          .well 
            = "http://thisisgrit.us/videos/detail/video.token"
      %tr
        %th
          Embed:
        %td
          .well
            = video.youtube_embed

%section#reccomend
  %h2
    We 
    %span
      Reccomend
  = render partial: "layouts/videos"

%section#comment
  %h2 
    Video
    %span
      Comments
  .fb-comments{'data-href'=>"http://example.com/comments", 'data-numposts'=>"10", 'data-colorscheme'=>"light"}

app/views/videos/edit.html.haml
%h1 Editing video

= render 'form'

= link_to 'Show', @video
\|
= link_to 'Back', videos_path

app/views/videos/index.html.haml
%h1 Listing videos

%table
  %tr
    %th
    %th
      Key
    %th
      Name
    %th
      Email
    %th
      Youtube URL
    %th
    %th
    %th

  - @videos.each do |video|
    %tr
      %td
        = image_tag(video.thumb_url, width: 89, height: 68)
      %td
        = video.key
      %td
        = video.name
      %td
        = link_to video.email, "mailto:"+video.email if video.email
      %td
        = link_to 'youtube url', video.youtube_url
      %td= link_to 'Show', video
      %td= link_to 'Edit', edit_video_path(video)
      %td= link_to 'Destroy', video, :method => :delete, :data => { :confirm => 'Are you sure?' }
%br

= link_to 'New Video', new_video_path

app/views/videos/new.html.haml
%h1 New video

= render 'form'

= link_to 'Back', videos_path

app/views/videos/show.html.haml
%p#notice= notice
- video = @video

.container
  = video.youtube_embed.html_safe
  %br/

  %table
    %tr
      %th
        Key:
      %td
        = video.key  
    %tr
      %th
        Name:
      %td
        = video.name
    %tr
      %th
        Email:
      %td
        = video.email
    %tr
      %th
        Thumbnail:
      %td
        = video.thumb_url
    %tr
      %th
        Youtube URL:
      %td
        = video.youtube_url
    %tr
      %th
        Youtube Embed
      %td
        = video.youtube_embed
  %strong
    Json Object:
  %br/
  = ap(video.json_object).html_safe

  = link_to 'Edit', edit_video_path(@video)
  \|
  = link_to 'Back', videos_path