config/routes.rb
Grit::Application.routes.draw do
  devise_for :users
  resources :user_settings

  resources :settings

  resources :contents

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :slides

  resources :endorsements

  resources :video_jobs

  resources :videos

  get "camera_tag_handler/create"

  root 'public#index'

  get '/about', to: 'public#about', as: :about
  get '/more', to: 'public#more', as: :more
  get '/share', to: 'public#share', as: :share

  post 'service/video_tag_handler', to: 'camera_tag_handler#create'

  get '/video/details/:token', to: 'public#details'

end

app/models/endorsement.rb
class Endorsement < ActiveRecord::Base
end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController
  before_action :authenticate_admin_user!
  before_action :set_endorsement, only: [:show, :edit, :update, :destroy]

  # GET /endorsements
  # GET /endorsements.json
  def index
    @endorsements = Endorsement.all
  end

  # GET /endorsements/1
  # GET /endorsements/1.json
  def show
  end

  # GET /endorsements/new
  def new
    @endorsement = Endorsement.new
  end

  # GET /endorsements/1/edit
  def edit
  end

  # POST /endorsements
  # POST /endorsements.json
  def create
    @endorsement = Endorsement.new(endorsement_params)

    respond_to do |format|
      if @endorsement.save
        format.html { redirect_to @endorsement, notice: 'Endorsement was successfully created.' }
        format.json { render action: 'show', status: :created, location: @endorsement }
      else
        format.html { render action: 'new' }
        format.json { render json: @endorsement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /endorsements/1
  # PATCH/PUT /endorsements/1.json
  def update
    respond_to do |format|
      if @endorsement.update(endorsement_params)
        format.html { redirect_to @endorsement, notice: 'Endorsement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @endorsement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /endorsements/1
  # DELETE /endorsements/1.json
  def destroy
    @endorsement.destroy
    respond_to do |format|
      format.html { redirect_to endorsements_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_endorsement
      @endorsement = Endorsement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def endorsement_params
      params.require(:endorsement).permit(:content, :credit, :order)
    end
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/views/endorsements/_form.html.haml
= form_for @endorsement do |f|
  - if @endorsement.errors.any?
    #error_explanation
      %h2= "#{pluralize(@endorsement.errors.count, "error")} prohibited this endorsement from being saved:"
      %ul
        - @endorsement.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.label :credit
    = f.text_field :credit
  .field
    = f.label :order
    = f.number_field :order
  .actions
    = f.submit 'Save'

app/views/endorsements/edit.html.haml
%h1 Editing endorsement

= render 'form'

= link_to 'Show', @endorsement
\|
= link_to 'Back', endorsements_path

app/views/endorsements/index.html.haml
%h1 Listing endorsements

%table
  %tr
    %th Content
    %th Credit
    %th Order
    %th
    %th
    %th

  - @endorsements.each do |endorsement|
    %tr
      %td= endorsement.content
      %td= endorsement.credit
      %td= endorsement.order
      %td= link_to 'Show', endorsement
      %td= link_to 'Edit', edit_endorsement_path(endorsement)
      %td= link_to 'Destroy', endorsement, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Endorsement', new_endorsement_path

app/views/endorsements/new.html.haml
%h1 New endorsement

= render 'form'

= link_to 'Back', endorsements_path

app/views/endorsements/show.html.haml
%p#notice= notice

%p
  %b Content:
  = @endorsement.content
%p
  %b Credit:
  = @endorsement.credit
%p
  %b Order:
  = @endorsement.order

= link_to 'Edit', edit_endorsement_path(@endorsement)
\|
= link_to 'Back', endorsements_path